name:  Go CI

# 1. WHEN to run this workflow
on:
  push:
    branches: [ "main" ] # Trigger on pushes to the 'main' branch
  
# 2. WHAT to run
jobs:
  build-and-test:
    # Use a standard, clean Linux environment for the runner
    runs-on: ubuntu-latest
    
    # 3. THE STEPS to follow
    steps:
      # Step 1: Check out the code from the repo
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up the specific Go version (1.22)
      - name: Set up Go 1.22
        uses: actions/setup-go@v5
        with:
          # --- Pinned Version Specified Here ---
          go-version: '1.22'
          cache: true 

      # Step 3: Download dependencies (go mod download)
      - name: Download Go Modules
        run: go mod download

      # Step 4: Run all tests
      - name: Run Tests
        # The '-v' flag provides verbose output
        run: go test -v ./...

      # Step 5: Build the application 
      - name: Build
        # This creates the executable binary in the current directory
        run: go build -v ./...